# Workflow name
name: Java CI with Gradle

# Trigger workflow on push or pull request to master branch
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Define jobs to run
jobs:
  # Job to build Java application
  build-java:

    # Run on latest Ubuntu runner
    runs-on: ubuntu-latest
    
    # Sequential steps to execute
    steps:
    # Checkout repository code
    - uses: actions/checkout@v2

    # Setup Java Development Kit 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Make gradlew file executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build project using Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Build and push Docker image to Docker Hub
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: sahilbelurkar12/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
